### ISSUE TITLE
Admin Dashboard needs to be its own lazy loaded module.

### ISSUE THREAD

**Issue by mtmulch** [mtmulch/mulchronedigital.com#37]
User dashboard turned out a lot heavier than I thought.

**Comment by avidtech** [comment]
Ur mom turned out a lot heavier than I thought.

JK, she's a nice lady.

Fucking school work man. Kill my face with gun bullet.

On Nov 5, 2017 9:32 PM, "Mike Mulchrone" <notifications@github.com> wrote:

User dashboard turned out a lot heavier than I thought.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mtmulch/Node.js-Angular5-Starter/issues/37>, or mute
the thread

**Comment by mtmulch** [comment]
Complete.
